language: objective-c
matrix:
    include:
        - name: "NeedleFoundationTests"
          script: xcodebuild test -project Foundation/NeedleFoundation.xcodeproj -scheme NeedleFoundationTests -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X'
